services:
  bankapp-discovery-service:
    build: ./discovery-service
    container_name: bankapp-discovery-service
    ports:
      - '8761:8761'
    expose:
      -  '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]  
      interval: 10s
      retries: 10
  bankapp-config-service:
    build: ./config-service
    container_name: bankapp-config-service
    ports:
      - '9999:9999'
    expose:
      -  '9999'
    environment: 
      - DISCOVERY_SERVICE_URL=http://bankapp-discovery-service:8761/eureka
    depends_on:
        bankapp-discovery-service:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]  
      interval: 10s
      retries: 10      
  bankapp-customer-service:
    build: ./customer-service
    container_name: bankapp-customer-service
    ports:
      - '8081:8081'
    expose:
      -  '8081'
    environment: 
      - DISCOVERY_SERVICE_URL=http://bankapp-discovery-service:8761/eureka  
      - CONFIG_SERVICE_URL=http://bankapp-config-service:9999  
    depends_on: 
        bankapp-config-service:
          condition: service_healthy 
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]  
      interval: 10s
      retries: 10          
  bankapp-account-service:
    build: ./account-service
    container_name: bankapp-account-service
    ports:
      - '8082:8082'
    expose:
      -  '8082'
    environment: 
      - DISCOVERY_SERVICE_URL=http://bankapp-discovery-service:8761/eureka  
      - CONFIG_SERVICE_URL=http://bankapp-config-service:9999  
    depends_on: 
        bankapp-customer-service:
          condition: service_healthy       
  bankapp-gateway-service:
    build: ./gateway-service
    container_name: bankapp-gateway-service
    ports:
      - '8888:8888'
    expose:
      -  '8888'
    environment: 
      - DISCOVERY_SERVICE_URL=http://bankapp-discovery-service:8761/eureka  
      - CONFIG_SERVICE_URL=http://bankapp-config-service:9999  
    depends_on: 
        bankapp-config-service:
          condition: service_healthy 
                